// Ed25519 public key used to verify signed casino licenses.
//
// The matching PRIVATE key lives OFFLINE on the release engineer's machine
// (see deploy/cli/README.md). Rotating this constant invalidates every
// previously issued license.dat file — do it deliberately.
//
// Format: raw 32-byte Ed25519 public key, base64-encoded.
// Generated by: node deploy/cli/generate-keys.mjs
//
// TODO(release): replace PLACEHOLDER with the real key before first prod build.
export const LICENSE_PUBLIC_KEY_B64 =
  "PLACEHOLDER_REPLACE_WITH_deploy_cli_license_public_b64";

export const LICENSE_KEY_VERSION = 1;
