#!/usr/bin/env bash
#
# update.sh — one-shot updater for an on-prem Casino System install.
#
# Usage on server (as root):
#   curl -fsSL https://raw.githubusercontent.com/<OWNER>/<REPO>/main/deploy/update.sh | sudo bash
#
# What it does:
#   1. Reads GITHUB_OWNER / GITHUB_REPO (and optional GITHUB_TOKEN) from /opt/casino-system/deploy/.env
#   2. Downloads latest source tarball of `main` branch from GitHub
#   3. Backs up .env, certs, postgres data — never touches them
#   4. rsyncs new sources over /opt/casino-system
#   5. Rebuilds cms-frontend with LOCAL database URL and restarts frontend + nginx
#
# Safe to re-run. Exits non-zero on any error.
#
set -euo pipefail

# ── Modes ────────────────────────────────────────────────────────────────────
# Default: full update (sources + DB seed/repair + rebuild cms-frontend & cms-sync)
# --frontend-only | FRONTEND_ONLY=1
#   Pulls new sources, rebuilds ONLY cms-frontend, restarts cms-frontend+nginx.
#   Does NOT touch the database (no seed-defaults.sql, no repair-local-schema.sql).
#   Does NOT rebuild cms-sync. Safe for UI-only patches.
FRONTEND_ONLY="${FRONTEND_ONLY:-0}"
for arg in "$@"; do
  case "$arg" in
    --frontend-only|-f) FRONTEND_ONLY=1 ;;
  esac
done

CMS_DIR="/opt/casino-system"
ENV_FILE="${CMS_DIR}/deploy/.env"
TS="$(date +%Y%m%d-%H%M%S)"
TMP_DIR="/tmp/cms-update-${TS}"
BACKUP_DIR="/opt/casino-system.bak.${TS}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[update]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn]${NC} $*"; }
die()  { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root (use sudo)"
[[ -d "$CMS_DIR" ]] || die "$CMS_DIR not found — is the system installed?"
[[ -f "$ENV_FILE" ]] || die "$ENV_FILE not found"

OWNER="${OWNER:-$(grep -E '^GITHUB_OWNER=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"')}"
REPO="${REPO:-$(grep -E '^GITHUB_REPO='  "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"')}"
TOKEN="${TOKEN:-$(grep -E '^GITHUB_TOKEN=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"' || true)}"
BRANCH="${BRANCH:-main}"

# Sensible defaults if still empty
OWNER="${OWNER:-pc-cms}"
REPO="${REPO:-casinosystem}"

[[ -n "$OWNER" && -n "$REPO" ]] || die "GITHUB_OWNER / GITHUB_REPO missing (pass OWNER=... REPO=... or add to $ENV_FILE)"

log "Repo:    $OWNER/$REPO  branch=$BRANCH"
log "Target:  $CMS_DIR"
log "Backup:  $BACKUP_DIR"

read_env_key() {
  grep -E "^$1=" "$ENV_FILE" | head -1 | cut -d= -f2- | sed -e "s/^'//" -e "s/'$//" -e 's/^"//' -e 's/"$//'
}

write_root_compose_env() {
  {
    echo "# Auto-generated by Casino System updater."
    echo "# Lets \`docker compose ...\` work from /opt/casino-system."
    echo "COMPOSE_FILE=deploy/docker-compose.yml"
    echo "COMPOSE_PROJECT_NAME=deploy"
    grep -vE '^COMPOSE_(FILE|PROJECT_NAME|ENV_FILES)=' "$ENV_FILE" 2>/dev/null || true
  } > "${CMS_DIR}/.env"
  if getent group docker >/dev/null 2>&1; then
    chgrp docker "${CMS_DIR}/.env" "$ENV_FILE" 2>/dev/null || true
    chmod 0640 "${CMS_DIR}/.env" "$ENV_FILE" 2>/dev/null || true
  else
    chmod 0644 "${CMS_DIR}/.env" "$ENV_FILE" 2>/dev/null || true
  fi
}

# 1. Check internet
if ! curl -fsS --max-time 8 -o /dev/null https://api.github.com 2>/dev/null; then
  die "No internet access to api.github.com"
fi

# 2. Download tarball
mkdir -p "$TMP_DIR"
TARBALL="${TMP_DIR}/src.tar.gz"
AUTH_HEADER=()
if [[ -n "${TOKEN:-}" && "$TOKEN" != "ghp_replace_me" ]]; then
  AUTH_HEADER=(-H "Authorization: Bearer $TOKEN")
  URL="https://api.github.com/repos/${OWNER}/${REPO}/tarball/${BRANCH}"
else
  URL="https://codeload.github.com/${OWNER}/${REPO}/tar.gz/refs/heads/${BRANCH}"
fi
log "Downloading $URL"
curl -fL "${AUTH_HEADER[@]}" -o "$TARBALL" "$URL" || die "Download failed"
SIZE=$(du -h "$TARBALL" | awk '{print $1}')
log "Got $SIZE"

# 2b. Signed OTA verification (opt-in). When RELEASE_SIG_URL is set in .env or
# passed as env, download the .sig and verify against /etc/casino-system/ota.pub
# BEFORE extraction. Refuses to proceed on signature mismatch.
RELEASE_SIG_URL="${RELEASE_SIG_URL:-$(grep -E '^RELEASE_SIG_URL=' "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"')}"
if [[ -n "$RELEASE_SIG_URL" && -f /etc/casino-system/ota.pub ]]; then
  SIGFILE="${TMP_DIR}/src.tar.gz.sig"
  log "Downloading signature $RELEASE_SIG_URL"
  curl -fL -o "$SIGFILE" "$RELEASE_SIG_URL" || die "Signature download failed"
  if [[ -x "${CMS_DIR}/deploy/ota-verify.sh" ]]; then
    bash "${CMS_DIR}/deploy/ota-verify.sh" "$TARBALL" "$SIGFILE" || die "OTA signature verification FAILED — refusing update"
    log "OTA signature verified ✓"
  else
    warn "ota-verify.sh missing — skipping signature check"
  fi
elif [[ -n "$RELEASE_SIG_URL" ]]; then
  die "RELEASE_SIG_URL set but /etc/casino-system/ota.pub missing — install ota.pub or unset RELEASE_SIG_URL"
fi

# 3. Extract
log "Extracting..."
tar -xzf "$TARBALL" -C "$TMP_DIR"
EXTRACTED=$(find "$TMP_DIR" -mindepth 1 -maxdepth 1 -type d | head -1)
[[ -d "$EXTRACTED" && -d "$EXTRACTED/deploy" ]] || die "Bad tarball: no deploy/ inside"

# 4. Backup current install
log "Creating backup at $BACKUP_DIR"
cp -a "$CMS_DIR" "$BACKUP_DIR"

# 5. Sync new source over old (preserve .env, certs, data)
log "Syncing new sources..."
rsync -a --delete \
  --exclude 'deploy/.env' \
  --exclude 'deploy/certs/' \
  --exclude 'deploy/postgres/data/' \
  --exclude 'deploy/dist/' \
  --exclude 'node_modules/' \
  --exclude '.git/' \
  "$EXTRACTED"/ "$CMS_DIR"/

# 6. Rebuild frontend + cms-sync + restart
cd "${CMS_DIR}/deploy"
write_root_compose_env

# 6a. Backfill missing CASINO_ID for installs that predate the placeholder UUID.
if ! grep -qE '^CASINO_ID=' "$ENV_FILE"; then
  log "Adding CASINO_ID placeholder to .env"
  echo 'CASINO_ID=00000000-0000-0000-0000-0000000000ca' >> "$ENV_FILE"
fi

# 6b. Re-apply seed defaults (roles matrix, placeholder casino, wallets, chip colors).
# Idempotent (ON CONFLICT DO NOTHING) — safe to run on existing installs.
# Skipped entirely in --frontend-only mode.
if [[ "$FRONTEND_ONLY" != "1" ]]; then
  if docker compose ps postgres --status=running 2>/dev/null | grep -q postgres; then
    PGPASSWORD_VALUE="$(read_env_key POSTGRES_PASSWORD)"
    if [[ -f "${CMS_DIR}/deploy/postgres/init/20-seed-defaults.sql" ]]; then
      log "Applying seed defaults (idempotent)..."
      docker compose exec -T -e PGPASSWORD="$PGPASSWORD_VALUE" postgres psql -h 127.0.0.1 -U postgres -d postgres \
        < "${CMS_DIR}/deploy/postgres/init/20-seed-defaults.sql" >/dev/null 2>&1 \
        && log "Seed defaults applied." \
        || warn "Seed defaults skipped (postgres not ready or already applied)."
    fi
    if [[ -f "${CMS_DIR}/deploy/postgres/repair-local-schema.sql" ]]; then
      log "Applying local schema repair (idempotent)..."
      docker compose exec -T -e PGPASSWORD="$PGPASSWORD_VALUE" postgres psql -h 127.0.0.1 -U postgres -d postgres -v ON_ERROR_STOP=1 \
        < "${CMS_DIR}/deploy/postgres/repair-local-schema.sql" >/dev/null 2>&1 \
        && log "Local schema repair applied." \
        || warn "Local schema repair skipped (postgres not ready)."
    fi
  fi
else
  log "FRONTEND_ONLY mode — skipping DB seed defaults and schema repair."
fi

# Frontend uses universal placeholder __CMS_ORIGIN_PLACEHOLDER__/api baked at build,
# rewritten to location.origin by docker/frontend-entrypoint.sh at container start.
EXPECTED_PLACEHOLDER="__CMS_ORIGIN_PLACEHOLDER__/api"
# Scope the Cloud-URL guard to the cms-frontend service block only.
# Other services (cms-sync) legitimately reference Cloud via CLOUD_URL for mesh sync.
FRONTEND_BLOCK="$(docker compose config 2>/dev/null | awk '
  /^  [a-zA-Z0-9_-]+:/ { svc=$1; sub(/:$/,"",svc); next }
  svc=="cms-frontend" { print }
')"
echo "$FRONTEND_BLOCK" | grep -q "VITE_SUPABASE_URL: ${EXPECTED_PLACEHOLDER}" \
  || die "docker-compose is not baking universal placeholder (${EXPECTED_PLACEHOLDER}) into cms-frontend"
echo "$FRONTEND_BLOCK" | grep -q "supabase.co" \
  && die "Refusing to update: cms-frontend service references a Cloud supabase.co URL"

docker image ls --format '{{.Repository}}:{{.Tag}}' | grep '^cms-frontend:' | xargs -r docker image rm -f 2>/dev/null || true

if [[ "$FRONTEND_ONLY" == "1" ]]; then
  log "Building cms-frontend ONLY (frontend-only mode, ~3-5 min)..."
  docker compose build --no-cache cms-frontend
  log "Restarting frontend + nginx..."
  docker compose up -d --force-recreate cms-frontend nginx
else
  log "Building cms-frontend + cms-sync (this may take 3-7 min)..."
  docker compose build --no-cache cms-frontend cms-sync
  log "Restarting frontend + nginx + cms-sync..."
  docker compose up -d cms-frontend nginx cms-sync
fi

# 7. Health check
log "Waiting for frontend..."
for i in $(seq 1 30); do
  if docker compose exec -T cms-frontend curl -fsS http://localhost/ -o /dev/null 2>/dev/null; then
    log "Frontend is up."
    break
  fi
  sleep 2
done

# 8. Cleanup tmp
rm -rf "$TMP_DIR"

echo
log "✓ Update finished. Backup kept at: $BACKUP_DIR"
log "  Open https://$(hostname -I | awk '{print $1}')/admin to verify."
