// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-casinos.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(auth2) {
  const token = auth2.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-casinos.ts
var list_casinos_default = defineTool({
  name: "list_casinos",
  title: "List casinos",
  description: "List the casinos the signed-in user can access (id, name, slug).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("casinos").select("id, name, slug").order("name");
    if (error) throw new ToolError(error.message);
    const casinos = (data ?? []).map((c) => ({ id: c.id, name: c.name, slug: c.slug ?? null }));
    return {
      content: [{ type: "text", text: JSON.stringify(casinos) }],
      structuredContent: { casinos }
    };
  }
});

// src/lib/mcp/tools/get-day-closings.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";
var isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD");
var get_day_closings_default = defineTool2({
  name: "get_day_closings",
  title: "Get day closings",
  description: "Read closed business-day results (tables, slots, cash desk) for one casino in a date range (max 62 days).",
  inputSchema: {
    casino_id: z.string().uuid().describe("Casino id from list_casinos."),
    from: isoDate.describe("First business date, YYYY-MM-DD."),
    to: isoDate.describe("Last business date, YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ casino_id, from, to }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    if (from > to) throw new ToolError2("'from' must be on or before 'to'");
    const days = (Date.parse(to) - Date.parse(from)) / 864e5;
    if (days > 62) throw new ToolError2("Range too long (max 62 days)");
    const { data, error } = await supabaseForUser(ctx).from("fin_day_closing").select("business_date, tables_result, slots_result, cashdesk_win, players_card_balance, drop_slots, net_win, notes").eq("casino_id", casino_id).gte("business_date", from).lte("business_date", to).order("business_date");
    if (error) throw new ToolError2(error.message);
    const closings = (data ?? []).map((d) => ({
      business_date: d.business_date,
      tables_result: d.tables_result == null ? null : Number(d.tables_result),
      slots_result: d.slots_result == null ? null : Number(d.slots_result),
      cashdesk_win: d.cashdesk_win == null ? null : Number(d.cashdesk_win),
      players_card_balance: d.players_card_balance == null ? null : Number(d.players_card_balance),
      drop_slots: d.drop_slots == null ? null : Number(d.drop_slots),
      net_win: d.net_win == null ? null : Number(d.net_win),
      notes: d.notes ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(closings) }],
      structuredContent: { closings }
    };
  }
});

// src/lib/mcp/tools/search-players.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var search_players_default = defineTool3({
  name: "search_players",
  title: "Search players",
  description: "Find players by name, nickname or phone (up to 25 results).",
  inputSchema: {
    query: z2.string().trim().min(2).max(60).describe("Part of the name, nickname or phone.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const q = query.replace(/[%,()]/g, " ");
    const { data, error } = await supabaseForUser(ctx).from("players").select("id, casino_id, full_name, nickname, phone, category, status, player_type").or(`full_name.ilike.%${q}%,nickname.ilike.%${q}%,phone.ilike.%${q}%`).neq("status", "merged").limit(25);
    if (error) throw new ToolError3(error.message);
    const players = (data ?? []).map((p) => ({
      id: p.id,
      casino_id: p.casino_id,
      full_name: p.full_name ?? null,
      nickname: p.nickname ?? null,
      phone: p.phone ?? null,
      category: p.category ?? null,
      status: p.status ?? null,
      player_type: p.player_type ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(players) }],
      structuredContent: { players }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rpehngjvwcnipvkouluu";
var mcp_default = defineMcp({
  name: "custom-cms",
  title: "Custom CMS",
  version: "0.1.0",
  instructions: "Read-only casino management tools. Start with `list_casinos` to get casino ids, then use `get_day_closings` for daily results or `search_players` to find players. Amounts are in TZS; dates are business days (07:00 EAT rollover).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_casinos_default, get_day_closings_default, search_players_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
