ALTER TABLE public.live_operation_start_events
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE OR REPLACE FUNCTION public.get_effective_live_start(_casino_id uuid, _business_date date)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT COALESCE(
    (SELECT e.effective_start_time
       FROM public.live_operation_start_events e
      WHERE e.casino_id = _casino_id
        AND e.business_date = _business_date
      ORDER BY e.seq DESC
      LIMIT 1),
    (SELECT NULLIF(c.shift_start, '') FROM public.casinos c WHERE c.id = _casino_id),
    '18:00'
  );
$$;